/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.eclipse.uml2.uml.Model;

public class App {

    private Model myUmlModel;

    public String getGreeting() {
        myUmlModel = null;
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
